Use DBusGMainLoop in utilities
Both utilities fail with

ERROR: To make asynchronous calls, receive signals or export objects,
D-Bus connections must be attached to a main loop by passing mainloop=...
to the constructor or calling dbus.set_default_main_loop(...)

Long ago D-Bus did begin to require a main loop, and this was added to
sugar-install-bundle in 2007 but the datastore utilities had not been
updated.

Fixes https://github.com/sugarlabs/sugar-datastore/issues/13

Fixes https://bugs.sugarlabs.org/ticket/4966