Convert dbus.ByteArray to <class int>
dbus.Int32 takes <class int> while initialization
'preview' is of type int
'timestamp' and 'creation_time' is of type dbus.Int32
Fixes error:
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py" line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/carquinyol/datastore.py", line 409, in find
    metadata = self._metadata_store.retrieve(uid,properties)
  File "/usr/lib/python3/dist-packages/carquinyol/metadatastore.py", line 84, in retrieve
    metadata[key] = dbus.Int32(value)
ValueError: invalid literal for int() with base 10: b''

Regression introduced in https://github.com/sugarlabs/sugar-datastore/commit/80fa75f4fed946bfae21495408849ffc59738754