Use Xapian commit method instead of flush
It was added in Xapian 1.1. xapian.WritableDatabase.flush() is
deprecated and removed in Xapian 2.0.

This fixes the following error using Xapian 2.0:
```
1782223286.247673 ERROR indexstore: 'WritableDatabase' object has no attribute 'flush'
Traceback (most recent call last):
  File "/usr/lib/python3.14/site-packages/carquinyol/indexstore.py", line 413, in _flush
    self._database.flush()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WritableDatabase' object has no attribute 'flush'
1782223286.248249 ERROR indexstore: Exception during database.flush()
```
Reference:
https://xapian.org/docs/bindings/python3/xapian.html#xapian.WritableDatabase.commit